services:
  notes-app-db:
    image: "postgres:18"
    networks:
      - notes-app
    env_file:
      - ./db.env
    volumes:
      - pgdata:/var/lib/postgresql
      - "./notes-app-backend/init.sql:/docker-entrypoint-initdb.d/init.sql"
  
  notes-app-backend:
    build:
      context: ./notes-app-backend
      target: prod
    env_file:
      - ./notes-app-backend/.env
    networks:
      - notes-app
    depends_on:
      - notes-app-db
    environment:
      NODE_ENV: production
    
  notes-app-frontend:
    build:
      context: ./notes-app-frontend
      target: prod
    ports:
      - "80:80"
    depends_on:
      - notes-app-backend
    networks:
      - notes-app
networks:
  notes-app:
volumes:
  pgdata: