services:
  notes-app-db:
    image: "postgres:18"
    networks:
      - notes-app
    env_file:
      - ./db.env
    volumes:
      - pgdata:/var/lib/postgresql
      - "./notes-app-backend/init.sql:/docker-entrypoint-initdb.d/init.sql"
    ports:
      - "5432:5432"
  
  notes-app-backend:
    build:
      context: ./notes-app-backend
      target: dev
    env_file:
      - ./notes-app-backend/.env
    networks:
      - notes-app
    volumes:
      - ./notes-app-backend:/app
      - /app/node_modules
    depends_on:
      - notes-app-db
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    
  notes-app-frontend:
    build:
      context: ./notes-app-frontend
      target: dev
    volumes:
      - "./notes-app-frontend:/app"
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - notes-app
    depends_on:
      - notes-app-backend
networks:
  notes-app:
volumes:
  pgdata: